version: 0.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
platform: Any CPU
build:
  project: WebApplication1
  verbosity: minimal
before_build:
  - nuget restore
